// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8VLcF8dWObF55o8UHa93aHhr5GVzOx8',
    appId: '1:274735071385:web:f62b0f541f35266ba4b808',
    messagingSenderId: '274735071385',
    projectId: 'flutter-xplat-forms',
    authDomain: 'flutter-xplat-forms.firebaseapp.com',
    databaseURL: 'https://flutter-xplat-forms-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-xplat-forms.appspot.com',
    measurementId: 'G-PB504HJMK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSzBqPA3ApOkgcw5EDV0UYTG7YLYWOopI',
    appId: '1:274735071385:android:b9689a4f2c7aa4a3a4b808',
    messagingSenderId: '274735071385',
    projectId: 'flutter-xplat-forms',
    databaseURL: 'https://flutter-xplat-forms-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-xplat-forms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFEfidhJYYtohy-UNv8o8s53D21fxiTA',
    appId: '1:274735071385:ios:147886e83915401da4b808',
    messagingSenderId: '274735071385',
    projectId: 'flutter-xplat-forms',
    databaseURL: 'https://flutter-xplat-forms-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-xplat-forms.appspot.com',
    iosBundleId: 'za.web.tech.flutterXplatForms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxFEfidhJYYtohy-UNv8o8s53D21fxiTA',
    appId: '1:274735071385:ios:cfa63e5f439731eea4b808',
    messagingSenderId: '274735071385',
    projectId: 'flutter-xplat-forms',
    databaseURL: 'https://flutter-xplat-forms-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-xplat-forms.appspot.com',
    iosBundleId: 'za.web.tech.flutterXplatForms.RunnerTests',
  );
}
